version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5557:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rescue

    volumes:
      - rescue_pg_data:/bitnami/postgresql

volumes:
  rescue_pg_data:
